spring:
  application:
    name: olx-login
#---------------------------------
# Database Connection
#---------------------------------
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/olxapp
  jpa:
    show-sql: true
#---------------------------------
# Application Logging Strategy
#---------------------------------
logging:
  level:
    com:
      zensar: debug
    org:
      springframework: warn
      hibernate:
        type:
          descriptor:
            sql: trace
#---------------------------------
# Actuator Endpoint Management
#---------------------------------
management:
  endpoints:
    web:
      exposure:
        include : "*"
#---------------------------------
# Eureka Client Configuration
#---------------------------------
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
#---------------------------------
# Misc Configuration
#---------------------------------
jwt:
  secret:
    key: ShVmYq3t6w9z$C&F)J@McQfTjWnZr4u7
server:
  port: 8081
#---------------------------------
