spring:
  application:
    name: olx-config-server
#---------------------------------
# Git Access For Cloud Config
#---------------------------------
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KishorJadhao1990/OlxAppConfigs.git
          username: KishorJadhao1990
          password: Kishor@1990
          clone-on-start: true
#---------------------------------
# Misc Configuration
server:
  port: 8888
#---------------------------------