#---------------------------------
# Git Access For Cloud Config
#---------------------------------
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KishorJadhao1990/OlxAppConfigs.git
          username: KishorJadhao1990
          password: Kishor@1990
#---------------------------------
