spring:
  application:
    name: olx-eureka-server
#---------------------------------
# Eureka Client Configuration
#---------------------------------
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#---------------------------------
# Misc Configuration
#---------------------------------
server:
  port: 8761
